### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_weinberg#36]
### Todo list

- [ ] 0,1,2로 표현된 클래스를 A,P,Q로 라벨링
[참고문헌](https://www.dropbox.com/s/2ae1g3d425zlh3r/Liberzon%20et%20al.%20-%202015%20-%20The%20Molecular%20Signatures%20Database%20Hallmark%20Gene%20Se.pdf?dl=0)

- [ ] single drug 머신러닝모델

- [x] 어트렉터 모델에 대해서, APC변이 세포주 추가
[Table S1J](https://github.com/jehoons/sbie_weinberg/tree/master/result/table_s1)

- [x] 어트렉터 모델에 대해서, 몇개의 셀라인을 추가 (COLO205, SW48 등)
[Table S5](https://github.com/jehoons/sbie_weinberg/tree/master/result/table_s5)

- [x] Attractor DB점검

- [x] Front page 수정하기 

- [x] 워크샵 발표자료 준비하기 
---
