### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_weinberg#59]
영현이
- [ ] 인터페이스 표준화 
- [ ] single drug dose response 

춘경이 - q-based & db-based - 통합
- [ ] ui 개선
- [ ] slurm, pbs 등 조사. 
- [ ] slurm 예제. 
- [ ] weinberg 컴퓨터에 서버 설치하기 
[slurm참고](https://github.com/jehoons/setup-slurm)
- [ ] 유전자정보, 처방 > 모델선택 하는 순서의 UI 개선

송제훈 
- [ ] 시뮬레이션 시나리오 디자인 
- [ ] 환자정보 입력으로 받기
- [ ] report data 개선하기 
참고문헌
[약물유사성네트워크](https://www.dropbox.com/s/668rmdfl4f6xqaj/Lo%20et%20al.%20-%202015%20-%20Large-scale%20chemical%20similarity%20networks%20for%20targe.PDF?dl=0)

--- 

5.18 회의 
암종 - 셀 매칭하기 
드럭-타겟 매칭하기
UI-JSON출력하기 
Single drug ML모델

**Comment by hanyh0807** [comment]
모듈 인풋 & 아웃풋 가이드라인
[att_sfa_example.pptx](https://github.com/jehoons/sbie_weinberg/files/919419/att_sfa_example.pptx)

**Comment by hanyh0807** [comment]
170427미
[170427.pptx](https://github.com/jehoons/sbie_weinberg/files/960483/170427.pptx)
팅

**Comment by hanyh0807** [comment]
Input json 구조

Patient
{
"cancer_type":"",
"mutation":"gene1\r\ngene2\r\ngene3",
"target1":"",
"target2":""
}


Cell line
{
"cancer_type":"",
"cellline":"",
"drug1":"",
"drug2":""
}

**Comment by jehoons** [comment]
[약물유사성네트워크a.pptx](https://github.com/jehoons/sbie_weinberg/files/1043569/a.pptx)
[170526_플랫폼팀_송제훈.pptx](https://github.com/jehoons/sbie_weinberg/files/1043570/170526_._.pptx)

**Comment by choonlog** [comment]
SLURM 진행상황 보고드립니다.
지난 주에 batch script 실행이 잘 되는 것을 확인하였고,
이번 한 주는 interactive jobs(parallel jobs) 구현을 위해 MPI study를 했습니다(openMPI, intelMPI).

**Comment by jehoons** [comment]
현재의 네트워크 수립 상황
[lung_networks_20170526_이종훈.xlsx](https://github.com/jehoons/sbie_weinberg/files/1076808/lung_networks_20170526_.xlsx)
[1-2. Network Team_Colorectal_박상민.xlsx](https://github.com/jehoons/sbie_weinberg/files/1076809/1-2.Network.Team_Colorectal_.xlsx)

**Comment by choonlog** [comment]
[170706_플랫폼팀_이춘경.pptx](https://drive.google.com/file/d/0B1xFxkWRHv8aekZ6T2Y5VnFkbEk/view?usp=sharing)

**Comment by choonlog** [comment]
[170720_플랫폼팀_이춘경.pptx](https://drive.google.com/open?id=0B1xFxkWRHv8aTnFxZ1oyQUVGT0k)

**Comment by choonlog** [comment]
[170803_플랫폼팀_이춘경.pptx](https://drive.google.com/open?id=0B1xFxkWRHv8aU1czb3EzNXhLbjQ)
